// <auto-generated />
using Domain.Enums;
using Infra.Repositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Infra.Repositories.Migrations.TenantManagement
{
    [DbContext(typeof(TenantManagementContext))]
    partial class TenantManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Models.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Dominio");

                    b.Property<string>("EmailAdministrador");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("LastModified");

                    b.Property<string>("Nome");

                    b.Property<string>("NomeAdministrador");

                    b.Property<byte>("Status");

                    b.Property<byte>("Tipo");

                    b.HasKey("Id");

                    b.HasIndex("Dominio")
                        .IsUnique()
                        .HasFilter("[Dominio] IS NOT NULL");

                    b.ToTable("Tenant");
                });
#pragma warning restore 612, 618
        }
    }
}
